# Nome da aplicação e porta do servidor
spring.application.name=scoutpro-service
server.port=3400

# Configurações do banco de dados (usando as credenciais do nosso docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/scoutpro 
spring.datasource.username=pgsql-scoutpro-master
spring.datasource.password=pgsql-scoutpro-password

# Gerenciamento das entidades e do banco de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra os SQLs gerados pelo Hibernate no console (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=MinhaChaveSecretaSuperSeguraECompridaParaOProjetoScoutPro2026!@#
api.security.token.expiration=2592000000